export const FETCH_DATA = "FETCH_DATA";

export const FETCHED_SUCCESSFULLY = "FETCHED_SUCCESSFULLY";

export const FETCH_FAILED = "FETCH_FAILED";

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const AUTH_START = 'AUTH_START';

export const AUTH_FAILURE = 'AUTH_FAILURE';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';

export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE';

