export const FETCH_DATA = "FETCH_DATA";
export const FETCHED_SUCCESSFULLY = "FETCHED_SUCCESSFULLY";
export const FETCH_FAILED = "FETCH_FAILED";

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';